services:
  - type: web
    name: catraca-anpr
    runtime: python
    rootDir: cloud
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: API_KEY
        generateValue: true
